from building import *

cwd  = GetCurrentDir()
src = Split('''
common/ring_buffer.c
sensor/sensor.c
sensor/calibration.c
moto/pwm.c
moto/moto.c
mpdc/mpdc.c
twowheel/twowheel_main.c
twowheel/param.c
math/light_matrix.c
filter/kalman.c
filter/filter.c
attitude/attitude_estimation.c
control/att_control.c
control/fuzzy_pid.c
wireless_ctrl/waveview.c
wireless_ctrl/rc.c
wireless_ctrl/sbus.c
''')

CPPPATH = [cwd + '/common', cwd + '/sensor', cwd + '/moto', cwd + '/mpdc', cwd + '/twowheel']
CPPPATH += [cwd + '/math', cwd + '/filter', cwd + '/attitude']
CPPPATH += [cwd + '/control', cwd + '/wireless_ctrl']

group = DefineGroup('Gorilla', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

