from building import *

cwd  = GetCurrentDir()
src = Split('''
sensor/sensor.c
moto/pwm.c
moto/moto.c
''')

CPPPATH = [cwd + '/sensor', cwd + '/moto']

group = DefineGroup('Gorilla', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

