from building import *

cwd  = GetCurrentDir()
src = Split('''
sensor/sensor.c
sensor/calibration.c
moto/pwm.c
moto/moto.c
mpdc/mpdc.c
twowheel/twowheel_main.c
twowheel/param.c
math/light_matrix.c
filter/kalman.c
filter/filter.c
attitude/attitude_estimation.c
''')

CPPPATH = [cwd + '/sensor', cwd + '/moto', cwd + '/mpdc', cwd + '/twowheel']
CPPPATH += [cwd + '/math', cwd + '/filter', cwd + '/attitude']

group = DefineGroup('Gorilla', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

