from building import *

cwd  = GetCurrentDir()
src = Split('''
mpu6050.c
drv_pwm.c
drv_quardencoder.c
''')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

