from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
stm32f4xx_it.c
usart.c
""")

# add Ethernet drivers.
if GetDepend('RT_USING_LWIP'):
    src += ['stm32f4xx_eth.c']

# add gpio drivers.
if GetDepend('RT_USING_PIN'):
    src += ['gpio.c']

if GetDepend('RT_USING_I2C'):
    src += ['stm32_i2c.c']

# add USB driver.
if GetDepend('RT_USING_USB_HOST'):
    src+= ['stm32f4xx_hcd.c']
    src+= ['usb_bsp.c']

if GetDepend('RT_USING_USB_DEVICE'):
    src+= ['usb_bsp.c']
    src+= ['stm32f4xx_dcd.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
